// <auto-generated />
namespace UtThienWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class editquantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editquantity));
        
        string IMigrationMetadata.Id
        {
            get { return "201912311105312_edit-quantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
