// <auto-generated />
namespace UtThienWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FormCreationDateFormFormStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FormCreationDateFormFormStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201912210839532_Form-Creation-Date&Form-Form-Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
